version: '2.0'
services:
  zookeeper0:
    build:
      context: .
      dockerfile: ../../../docker/leongu/zookeeper/Dockerfile
    image: leongu2003/zookeeper:latest
    container_name: zookeeper0
    hostname: zookeeper0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_ID: 0
      ZOOKEEPER_SERVERS: server.0=zookeeper0:2888:3888
  kafka0:
    build:
      context: .
      dockerfile: ../../../docker/leongu/kafka/Dockerfile
    image: leongu2003/kafka:latest
    container_name: kafka0
    hostname: kafka0
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper0:2181
      BROKER_ID: 0
      BROKER_PORT: 9092
      ADVERTISED_HOST_NAME: kafka0
      HOST_NAME: kafka0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper0
    expose:
      - 9092
#    links:
#      - zookeeper